kind: DeploymentConfig
apiVersion: v1
metadata:
  name: git-webhook-proxy-server
spec:
  replicas: 1
  selector:
    name: git-webhook-proxy-server
  template:
    metadata:
      labels:
        name: git-webhook-proxy-server
        CI_COMMIT_SHA: 5877e6872c46b2972b78e7e69035397ed259caae
    spec:
      containers:
      - name: git-webhook-proxy-server
        image: registry.saas.hand-china.com/test/git-webhook-proxy-server:master-5877e687
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: sit
        - name: EUREKA_DEFAULT_ZONE
          value: http://hap-register-server:8000/eureka/
        resources:
          requests:
            memory: 256Mi
          limits:
            memory: 1024Mi
  triggers:
  - type: ConfigChange
  strategy:
    type: Rolling
  paused: false
  revisionHistoryLimit: 2
  minReadySeconds: 0


---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: git-webhook-proxy-server
  name: git-webhook-proxy-server
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    name: git-webhook-proxy-server

---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: git-webhook-proxy-server
  name: git-webhook-proxy-server
spec:
  to:
    kind: Service
    name: git-webhook-proxy-server
    weight: 100
  wildcardPolicy: None
